# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autenticador.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61utenticador.proto\x12\x0c\x61utenticador\"\xc5\x01\n\x15\x41uthenticationRequest\x12\x13\n\x06nombre\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1d\n\x10lugar_nacimiento\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1c\n\x0f\x61nno_nacimiento\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x17\n\ncontrasena\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\t\n\x07_nombreB\x13\n\x11_lugar_nacimientoB\x12\n\x10_anno_nacimientoB\r\n\x0b_contrasena\"W\n\x13\x41uthenticationReply\x12\x14\n\x07message\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06status\x18\x02 \x01(\x08H\x01\x88\x01\x01\x42\n\n\x08_messageB\t\n\x07_status2\xbf\x01\n\x0c\x41utenticador\x12V\n\nautenticar\x12#.autenticador.AuthenticationRequest\x1a!.autenticador.AuthenticationReply\"\x00\x12W\n\x0b\x61utenticar2\x12#.autenticador.AuthenticationRequest\x1a!.autenticador.AuthenticationReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autenticador_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHENTICATIONREQUEST._serialized_start=37
  _AUTHENTICATIONREQUEST._serialized_end=234
  _AUTHENTICATIONREPLY._serialized_start=236
  _AUTHENTICATIONREPLY._serialized_end=323
  _AUTENTICADOR._serialized_start=326
  _AUTENTICADOR._serialized_end=517
# @@protoc_insertion_point(module_scope)
